### ISSUE TITLE
can't find mathfu on gradle

### ISSUE THREAD

**Issue by MarcoNordio1** [googlesamples/android-vulkan-tutorials#18]
Hi,
I'm try to run tutorial04_first_window but when I expand "Gradle" panel inside Android Studio( right hand edge of IDE) I can see only "tutorial04_first_window" and ":app". How can I solve this?

**Comment by ggfan** [comment]
you are correct, this set of samples are not using mathfu ( no transformation involved ), suppose the next set of samples will use it.  you could try it out as:

- your settings.gradle, add sth like:
```java
include ':mathfu'
project(':mathfu').projectDir = new File(settingsDir, '../common/mathfu')
````
- app/build.gradle, add:
```java
tasks.whenTaskAdded { task ->
    if (task.name.contains('compile')) {
        task.dependsOn ":mathfu:get_mathfu"
    }
}
```
this should get you going or close to get you going for mathfu
