### ISSUE TITLE
get gpuCount is 0

### ISSUE THREAD

**Issue by leihonh** [googlesamples/android-vulkan-tutorials#19]
If I get gpuCount = 0, this could be seen that My Android device is not support vulkan, right? 

My Android device is Nexus 6(Android 7.0, API 24)

**Comment by ggfan** [comment]
right. it is does not support Vulkan, nexus5X and 6p would do it. If you are using the sample here, I would expect it failed during vulkan wrapper initialization function
`int InitVulkan(void);`
in file `vulkan_wrapper.cpp`
