### ISSUE TITLE
Android-M Support

### ISSUE THREAD

**Issue by victorv** [googlesamples/android-vulkan-tutorials#2]
Will Vulkan be supported on Android-M?

**Comment by ggfan** [comment]
It is meant for N with Nexus devices, NDK is ready to use out of the box for android -N;
It also depends on what your devices' supportability:  if they have driver and loader on it, you are technically ready:  
   1) use vulkan headers from android-N NDK
   2) use wrappers [like this repo and others] / loader stub in android-N Ndk

**Comment by victorv** [comment]
@ggfan - Thanks. I converted the samples to M.
