### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rivaldo4t** [googlesamples/android-vulkan-tutorials#20]
CMake can not determine linker language for target: vktuts
Studio 2.3.1 
NDK 14.1.3816874 
Cmake 3.6.3155560

**Comment by ggfan** [comment]
yeah, I think you meant the tutorial03 which building validation layers.  it is merged and fixed; the real thing behind this is to have this layer build inside the ndk so app side never need to deal with ndk file location changes.  Will chase after that, stay tuned.
