### ISSUE TITLE
VulkanLayerValidationTestsa.apk crashing in vkCreateGraphicsPipelines

### ISSUE THREAD

**Issue by ajaybedi** [googlesamples/android-vulkan-tutorials#30]
Build fingerprint: 'samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQE7:user/release-keys'
07-06 14:13:27.906 29474 29474 F DEBUG   : Revision: '8'
07-06 14:13:27.906 29474 29474 F DEBUG   : ABI: 'arm64'
07-06 14:13:27.906 29474 29474 F DEBUG   : pid: 28517, tid: 28530, name: Thread-5  >>> com.example.VulkanLayerValidationTests <<<
07-06 14:13:27.906 29474 29474 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14
07-06 14:13:27.906 29474 29474 F DEBUG   :     x0   00000071addcee88  x1   0000000000000003  x2   0000000000000000  x3   0000000000000001
07-06 14:13:27.906 29474 29474 F DEBUG   :     x4   00000071addceedc  x5   000000719b388e00  x6   000000719b388000  x7   0000000000000000
07-06 14:13:27.906 29474 29474 F DEBUG   :     x8   00000071a38b9700  x9   0000000000000001  x10  000000719b388000  x11  00000071a38b9700
07-06 14:13:27.906 29474 29474 F DEBUG   :     x12  00000071a38b9700  x13  0000000000000000  x14  0000000000000000  x15  00000071addcee88
07-06 14:13:27.906 29474 29474 F DEBUG   :     x16  00000071a38b9700  x17  00000071a38b9700  x18  0000000000000000  x19  00000071a36ab508
07-06 14:13:27.906 29474 29474 F DEBUG   :     x20  000000718c2791d0  x21  0000000000000000  x22  0000000000000000  x23  0000000000000000
07-06 14:13:27.906 29474 29474 F DEBUG   :     x24  00000071a38b9700  x25  00000071addcee88  x26  00000071addceeb0  x27  00000071a38b9700
07-06 14:13:27.906 29474 29474 F DEBUG   :     x28  0000000000000000  x29  00000071addcf7d0  x30  000000719a1fb5e0
07-06 14:13:27.906 29474 29474 F DEBUG   :     sp   00000071addceda0  pc   000000719a1fb5e8  pstate 0000000080000000
07-06 14:13:27.921 29474 29474 F DEBUG   : 
07-06 14:13:27.921 29474 29474 F DEBUG   : backtrace:
07-06 14:13:27.921 29474 29474 F DEBUG   :     #00 pc 00000000004715e8  /system/vendor/lib64/egl/libGLES_mali.so
07-06 14:13:27.921 29474 29474 F DEBUG   :     #01 pc 0000000000471ffc  /system/vendor/lib64/egl/libGLES_mali.so (vkCreateGraphicsPipelines+496)

**Comment by ggfan** [comment]
which sample is this one for? Sorry for the delay. Tutorial02 and tutorial03 here on purposely left a bug to trigger validation layers,  but does not seem you are using samples, though

**Comment by cnorthrop** [comment]
VulkanLayerValidationTests are maintained upstream in [Vulkan-LoaderAndValidationLayers](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers).  I believe this issue has already been submitted against Mali.

**Comment by ggfan** [comment]
Thanks, we could close this one here then.

**Comment by ajaybedi** [comment]
I see this issue in Pixel XL as well. Can it be due to old Vulkan drivers ?

**Comment by cnorthrop** [comment]
Not all tests in the layer validation tests pass on all devices.  If you can capture which test is crashing, I'll let you know if that is an expected failure.  We tend to use negative gtest filters to skip test with known problems, i.e.:
`./test_APK.sh -s <serial> -p <platform_name> -f -<test_name>
`
