### ISSUE TITLE
tutorial05_triangle ./gradlew assembleDebug build fails with "unknown type name 'android_app'"

### ISSUE THREAD

**Issue by cirosantilli** [googlesamples/android-vulkan-tutorials#36]
```
/data/git/android-vulkan-tutorials/tutorial05_triangle/app/src/main/jni/VulkanMain.hpp:19:17: error: unknown type name 'android_app'
bool InitVulkan(android_app* app);
                ^
1 error generated.
ninja: build stopped: subcommand failed.
:app:externalNativeBuildDebug FAILED
```

Android Studio 2.3.3, SDK 26, NDK 15.2.

I can successfully build and run NDK GLES examples.

Up to tutorial 4 build, but fail to run on HiKey960 with SIGSEGV for me as in: https://github.com/SaschaWillems/Vulkan/issues/389

**Comment by ggfan** [comment]
Ok,looks like you get it handled in that repo.  we could close this one too then. Thanks for reporting the issue

**Comment by cirosantilli** [comment]
@ggfan no, that was a runtime failure, this is a build failure.

**Comment by ggfan** [comment]
Oh, no, will have a look at it.

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-vulkan-tutorials/pull/37
should fix it. please review, thanks!

**Comment by ggfan** [comment]
kindly let me know whether that fix the things. thanks!

**Comment by cirosantilli** [comment]
Thanks Gerry, the patch works, all running on my board just fine, I had gone to sleep yesterday :-)

**Comment by ggfan** [comment]
thanks!
