### ISSUE TITLE
VkQueueFamilyProperties not queried before VkCreateDevice

### ISSUE THREAD

**Issue by Qining** [googlesamples/android-vulkan-tutorials#38]
Not a big issue, but different platform may have different queue families and the QueueFamily[0] may not support graphics rendering.

**Comment by ggfan** [comment]
yeah, that is good point.  The spec at the beginning though said that all queues and devices must have the same functionality for Android ( for desktop, it could vary ).  May you help double check it?

**Comment by Qining** [comment]
Right, so the surface support is not a problem anymore, but strictly speaking we still need to check the VK_QUEUE_GRAPHICS_BIT before we draw anything by the queue. Anyway, not a big deal though.

**Comment by ggfan** [comment]
thanks, will look at it together with other 2 issues you reported.
