### ISSUE TITLE
Initial layout of image must be either UNDEFINED or PREINITIALIZED

### ISSUE THREAD

**Issue by Qining** [googlesamples/android-vulkan-tutorials#39]
The `VkImageCreateInfo` does not specifies what value will be there in the create_info. According to the spec, the initial layout must be either VK_IMAEG_LAYOUT_UNDEFINED or VK_IMAGE_LAYOUT_PREINITIALIZED.

**Comment by ggfan** [comment]
this should be fixed now with https://github.com/googlesamples/android-vulkan-tutorials/pull/43.
