### ISSUE TITLE
How to use dlopen() on Android 8?

### ISSUE THREAD

**Issue by RPG3D** [googlesamples/android-vulkan-tutorials#57]
In my test ndk app, dlopen() reutrn nullptr.
```extern "C" JNIEXPORT void JNICALL
Java_com_github_rpg3d_sword2android_MainActivity_runGame(JNIEnv* env, jobject /* this */)
{

    void* handle = dlopen("libvulkan.so", RTLD_NOW|RTLD_LOCAL);
    char* loaderror = (char *) dlerror();
    Game game;
    game.run();

}

**Comment by RPG3D** [comment]
> that should be the way.  Is Vulkan supported on the device?

yes. my device can run your LoadVulkan sample, but not my own test app

**Comment by ggfan** [comment]
I am not sure what the problem is. you are also using native-activity? ( not sure that matters at all)

Re-run the app while keep "adb logcat" running on command line, see if you could have some clue from there ( adb logcat ): it normally throw error message ( but buried in million of other non-related messages ) :-(

**Comment by RPG3D** [comment]
In single module it runs well. but in multi module app didn't.
can you give me some  some help ? I am portting an old 2D PC game to Android, but failed...
https://github.com/RPG3D/Sword2

**Comment by Andreyogld3d** [comment]
@RPG3D, try to use [vulkan_wrapper.cpp](https://github.com/googlesamples/android-vulkan-tutorials/blob/master/common/vulkan_wrapper/vulkan_wrapper.cpp) instead of manually loading of Vulkan API functions

**Comment by RPG3D** [comment]
> @RPG3D, try to use [vulkan_wrapper.cpp](https://github.com/googlesamples/android-vulkan-tutorials/blob/master/common/vulkan_wrapper/vulkan_wrapper.cpp) instead of manually loading of Vulkan API functions

thanks, I will do some test
