### ISSUE TITLE
Segmentation fault when Tutorial 05 is closed

### ISSUE THREAD

**Issue by arilow** [googlesamples/android-vulkan-tutorials#76]
Hi!! 

I found that when the app of the tutorial 5 is closed, I get a segmentation fault.

I think that [this](https://github.com/googlesamples/android-vulkan-tutorials/blob/master/tutorial05_triangle/app/src/main/jni/VulkanMain.cpp#L267) line is causing it. Because it is cleaning the memory allocate by the vkImages that will also be cleaned when destroying the swapchain.

If you take a look at the [Vulkan toturial](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain), you will see this: 
<img width="1012" alt="Screen Shot 2021-10-25 at 15 02 20" src="https://user-images.githubusercontent.com/43258762/138750343-3d1b76bf-669d-4178-8ba7-2ad7f03cb155.png">

```
"The images were created by the implementation for the swap chain and they will be automatically cleaned up once the swap chain has been destroyed, therefore we don't need to add any cleanup code."
```

**Comment by ggfan** [comment]
thank you for filing the issue: this should be fixed now.
