### ISSUE TITLE
tutorial06 shaderc ndk build error

### ISSUE THREAD

**Issue by Leon-Zhang** [googlesamples/android-vulkan-tutorials#79]
I was building shaderc with ndk r23 with command line given in tutorial 06 readme, it gives error when doing combine:
```
"[arm64-v8a] Combine: libshaderc_combined.a <= libglslang.a libOGLCompiler.a libOSDependent.a libshaderc.a libshaderc_util.a libSPIRV.a libHLSL.a libSPIRV-Tools.a libSPIRV-Tools-opt.a"
'D:/ProgramFiles/android-ndk-r23b/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar' is not recognized as an internal or external command,
operable program or batch file.
make: *** [D:/ProgramFiles/android-ndk-r23b/sources/third_party/shaderc/Android.mk:77: obj/local/arm64-v8a/libshaderc_combined.a] Error 1

```
I have checked there is no file named "aarch64-linux-android-ar" with any extension but only "aarch64-linux-android-as.exe" presents, is there any version mismatch problem I'm possibly encountering? Thanks in advance.

**Comment by ggfan** [comment]
This is ndk r23b specific issue,  please use another version, such as 25.1.893739 instead. Thank you for filing the issue.
